apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-uploads-pvc
  namespace: documentstorage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: documentstorage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: europe-north2-docker.pkg.dev/project-c257fdcb-0ada-47dd-add/documentstorage/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: documentstorage-config
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documentstorage-secret
                  key: MSSQL_SA_PASSWORD
            - name: JwtSettings__SecretKey
              valueFrom:
                secretKeyRef:
                  name: documentstorage-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: api-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: documentstorage
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
