apiVersion: v1
kind: ConfigMap
metadata:
  name: documentstorage-config
  namespace: documentstorage
data: 
   ApiSettings__BaseUrl: "http://api-svc:8080"
   JwtSettings__Issuer: "DocumentStorage"
   JwtSettings__Audience: "DocumentStorageUsers"
   ASPNETCORE_ENVIRONMENT: "Development"
