apiVersion: v1
kind: Secret
metadata:
  name: documentstorage-secret
  namespace: documentstorage
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "reallyStrongPassword123!"
  JWT_SECRET: "ThisIsMySecretKeyForJWTTokenGenerationAndValidation1234567890"
  ConnectionStrings__Default: "Server=tcp:sqlserver-svc.documentstorage.svc.cluster.local,1433;Database=DocumentStorageDB;User Id=sa;Password=reallyStrongPassword123!;Encrypt=True;TrustServerCertificate=True;Connect Timeout=60;"
  ConnectionStrings__DefaultConnection: "Server=tcp:sqlserver-svc.documentstorage.svc.cluster.local,1433;Database=DocumentStorageDB_CodeFirst;User Id=sa;Password=reallyStrongPassword123!;Encrypt=True;TrustServerCertificate=True;Connect Timeout=60;"
