apiVersion: v1
kind: Secret
metadata:
  name: documentstorage-secret
  namespace: documentstorage
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "reallyStrongPassword123!"
  JWT_SECRET: "ThisIsMySecretKeyForJWTTokenGenerationAndValidation1234567890"